#pragma once

enum AggregateInstanceStream_t : uint8_t  // sizeof 0x1
{
    AGGREGATE_INSTANCE_STREAM_NONE = 0,
    AGGREGATE_INSTANCE_STREAM_LIGHTMAPUV_UNORM16 = 1,
    AGGREGATE_INSTANCE_STREAM_VERTEXTINT_UNORM8 = 2,
    AGGREGATE_INSTANCE_STREAM_VERTEXBLEND_UNORM8 = 4,
    AGGREGATE_INSTANCE_STREAM_COLOR_UNORM8 = 8,
};
