#pragma once

enum AssetEditInfoFilterFunc_t : uint32_t  // sizeof 0x4
{
    ASSET_FILTER_EQUAL = 0,
    ASSET_FILTER_NOT_EQUAL = 1,
    ASSET_FILTER_EQUAL_OR_MISSING = 2,
    ASSET_FILTER_NOT_EQUAL_OR_MISSING = 3,
    ASSET_FILTER_LESS = 4,
    ASSET_FILTER_LESS_EQUAL = 5,
    ASSET_FILTER_GREATER = 6,
    ASSET_FILTER_GREATER_EQUAL = 7,
    ASSET_FILTER_CONTAINS = 8,
    ASSET_FILTER_DOES_NOT_CONTAIN = 9,
    ASSET_FILTER_DEPREF_ASSET = 10,
    ASSET_FILTER_DEPREF_BY_ASSET = 11,
    ASSET_FILTER_PARENTS_ASSET = 12,
    ASSET_FILTER_PARENTED_BY_ASSET = 13,
    ASSET_FILTER_REF_SUBASSET = 14,
    ASSET_FILTER_DEF_SUBASSET = 15,
    ASSET_FILTER_EXACT_DEPREF_ASSET = 16,
    ASSET_FILTER_EXACT_DEPREF_BY_ASSET = 17,
    ASSET_FILTER_EXACT_PARENTS_ASSET = 18,
    ASSET_FILTER_EXACT_PARENTED_BY_ASSET = 19,
    ASSET_FILTER_EXACT_REF_SUBASSET = 20,
    ASSET_FILTER_EXACT_DEF_SUBASSET = 21,
    ASSET_FILTER_FUNC_COUNT = 22,
};
