#pragma once

class C_SceneEntity : public C_PointEntity /*0x0*/  // sizeof 0x658, align 0x8 [vtable] (client) {MNetworkVarNames MNetworkVarNames MNetworkVarNames MNetworkVarNames MNetworkVarNames MNetworkVarNames MNetworkVarNames MNetworkVarNames}
{
public:
    char _pad_0000[0x5F8]; // offset 0x0
    bool m_bIsPlayingBack; // offset 0x5F8, size 0x1, align 1 | MNetworkEnable MNotSaved
    bool m_bPaused; // offset 0x5F9, size 0x1, align 1 | MNetworkEnable MNotSaved
    bool m_bMultiplayer; // offset 0x5FA, size 0x1, align 1 | MNetworkEnable MNotSaved
    bool m_bAutogenerated; // offset 0x5FB, size 0x1, align 1 | MNetworkEnable MNotSaved
    bool m_bAllRequirementsComplete; // offset 0x5FC, size 0x1, align 1 | MNetworkEnable MNotSaved
    char _pad_05FD[0x3]; // offset 0x5FD
    float32 m_flForceClientTime; // offset 0x600, size 0x4, align 4 | MNetworkEnable MNetworkChangeCallback MNotSaved
    uint16 m_nSceneStringIndex; // offset 0x604, size 0x2, align 2 | MNetworkEnable MNetworkPriority MNotSaved
    bool m_bClientOnly; // offset 0x606, size 0x1, align 1 | MNotSaved
    char _pad_0607[0x1]; // offset 0x607
    CHandle< C_BaseModelEntity > m_hOwner; // offset 0x608, size 0x4, align 4 | MNotSaved
    char _pad_060C[0x4]; // offset 0x60C
    C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > > m_hActorList; // offset 0x610, size 0x18, align 8 | MNetworkEnable MNetworkPriority MNotSaved
    bool m_bWasPlaying; // offset 0x628, size 0x1, align 1 | MNotSaved
    char _pad_0629[0xF]; // offset 0x629
    CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents; // offset 0x638, size 0x18, align 8 | MNotSaved
    float32 m_flCurrentTime; // offset 0x650, size 0x4, align 4 | MNotSaved
    char _pad_0654[0x4]; // offset 0x654
};
