#pragma once

class C_SceneEntity : public C_PointEntity /*0x0*/  // sizeof 0x668, align 0x8 [vtable] (client)
{
public:
    char _pad_0000[0x608]; // offset 0x0
    bool m_bIsPlayingBack; // offset 0x608, size 0x1, align 1 | MNotSaved
    bool m_bPaused; // offset 0x609, size 0x1, align 1 | MNotSaved
    bool m_bMultiplayer; // offset 0x60A, size 0x1, align 1 | MNotSaved
    bool m_bAutogenerated; // offset 0x60B, size 0x1, align 1 | MNotSaved
    bool m_bAllRequirementsComplete; // offset 0x60C, size 0x1, align 1 | MNotSaved
    char _pad_060D[0x3]; // offset 0x60D
    float32 m_flForceClientTime; // offset 0x610, size 0x4, align 4 | MNotSaved
    uint16 m_nSceneStringIndex; // offset 0x614, size 0x2, align 2 | MNotSaved
    bool m_bClientOnly; // offset 0x616, size 0x1, align 1 | MNotSaved
    char _pad_0617[0x1]; // offset 0x617
    CHandle< C_BaseModelEntity > m_hOwner; // offset 0x618, size 0x4, align 4 | MNotSaved
    char _pad_061C[0x4]; // offset 0x61C
    C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > > m_hActorList; // offset 0x620, size 0x18, align 8 | MNotSaved
    bool m_bWasPlaying; // offset 0x638, size 0x1, align 1 | MNotSaved
    char _pad_0639[0xF]; // offset 0x639
    CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents; // offset 0x648, size 0x18, align 8 | MNotSaved
    float32 m_flCurrentTime; // offset 0x660, size 0x4, align 4 | MNotSaved
    char _pad_0664[0x4]; // offset 0x664
};
