#pragma once

class CMapInfo : public C_PointEntity /*0x0*/  // sizeof 0x630, align 0x8 [vtable] (client)
{
public:
    char _pad_0000[0x600]; // offset 0x0
    int32 m_iBuyingStatus; // offset 0x600, size 0x4, align 4
    float32 m_flBombRadius; // offset 0x604, size 0x4, align 4
    int32 m_iPetPopulation; // offset 0x608, size 0x4, align 4
    bool m_bUseNormalSpawnsForDM; // offset 0x60C, size 0x1, align 1
    bool m_bDisableAutoGeneratedDMSpawns; // offset 0x60D, size 0x1, align 1
    char _pad_060E[0x2]; // offset 0x60E
    float32 m_flBotMaxVisionDistance; // offset 0x610, size 0x4, align 4
    int32 m_iHostageCount; // offset 0x614, size 0x4, align 4
    bool m_bFadePlayerVisibilityFarZ; // offset 0x618, size 0x1, align 1
    bool m_bRainTraceToSkyEnabled; // offset 0x619, size 0x1, align 1
    bool m_bGPUCullSkybox; // offset 0x61A, size 0x1, align 1
    char _pad_061B[0x1]; // offset 0x61B
    float32 m_flEnvRainStrength; // offset 0x61C, size 0x4, align 4
    float32 m_flEnvPuddleRippleStrength; // offset 0x620, size 0x4, align 4
    float32 m_flEnvPuddleRippleDirection; // offset 0x624, size 0x4, align 4
    float32 m_flEnvWetnessCoverage; // offset 0x628, size 0x4, align 4
    float32 m_flEnvWetnessDryingAmount; // offset 0x62C, size 0x4, align 4
};
