#pragma once

enum EAbilityTargetingLocation_t : uint32_t  // sizeof 0x4
{
    CITADEL_ABILITY_TARGETING_LOCATION_NONE = 0,
    CITADEL_ABILITY_TARGETING_LOCATION_SELF = 1,
    CITADEL_ABILITY_TARGETING_LOCATION_UNIT = 2,
    CITADEL_ABILITY_TARGETING_LOCATION_GROUND = 3,
    CITADEL_ABILITY_TARGETING_LOCATION_UNIT_OR_GROUND = 4,
    CITADEL_ABILITY_TARGETING_LOCATION_FIXED_RANGE_GROUND = 5,
    CITADEL_ABILITY_TARGETING_LOCATION_MINIMAP_GROUND = 6,
    CITADEL_ABILITY_TARGETING_LOCATION_MINIMAP_UNIT = 7,
    CITADEL_ABILITY_TARGETING_LOCATION_CUSTOM = 8,
    CITADEL_ABILITY_TARGETING_LOCATION_DEPLOYED_OBJECT = 9,
    CITADEL_ABILITY_TARGETING_LOCATION_COUNT = 10,
};
