#pragma once

enum EAbilityTargetingShape_t : uint32_t  // sizeof 0x4
{
    CITADEL_ABILITY_TARGETING_SHAPE_NONE = 0,
    CITADEL_ABILITY_TARGETING_SHAPE_SPHERE = 1,
    CITADEL_ABILITY_TARGETING_SHAPE_LINE = 2,
    CITADEL_ABILITY_TARGETING_SHAPE_CIRCLE = 3,
    CITADEL_ABILITY_TARGETING_SHAPE_CONE = 4,
    CITADEL_ABILITY_TARGETING_SHAPE_CAPSULE = 5,
    CITADEL_ABILITY_TARGETING_SHAPE_COUNT = 6,
};
