#pragma once

enum ECitadelPingWheelMessageType_t : uint32_t  // sizeof 0x4
{
    CITADEL_PING_WHEEL_PREGAME = 0,
    CITADEL_PING_WHEEL_INPROGRESS = 1,
    CITADEL_PING_WHEEL_DISABLED_WHILE_DEAD = 2,
    CITADEL_PING_WHEEL_POSTGAME = 3,
    CITADEL_PING_WHEEL_CONTEXTUAL = 4,
    CITADEL_PING_WHEEL_SUBNAV = 5,
    CITADEL_PING_WHEEL_COUNT = 6,
};
