#pragma once

enum ECitadelCombatLogTypes : uint32_t  // sizeof 0x4
{
    k_eCitadelCombatLog_Invalid = -1,
    k_eCitadelCombatLog_Damage = 0,
    k_eCitadelCombatLog_Heal = 1,
    k_eCitadelCombatLog_ModifierAdd = 2,
    k_eCitadelCombatLog_ModifierRemove = 3,
    k_eCitadelCombatLog_Death = 4,
    k_eCitadelCombatLog_AbilityUse = 5,
    k_eCitadelCombatLog_AbilityTrigger = 42,
    k_eCitadelCombatLog_ItemUse = 6,
    k_eCitadelCombatLog_Location = 7,
    k_eCitadelCombatLog_CurrencyChange = 8,
    k_eCitadelCombatLog_ItemPurchase = 11,
    k_eCitadelCombatLog_SoulSecure = 10,
    k_eCitadelCombatLog_Multikill = 15,
    k_eCitadelCombatLog_Killstreak = 16,
    k_eCitadelCombatLog_ObjectiveKill = 17,
    k_eCitadelCombatLog_FirstBlood = 18,
    k_eCitadelCombatLog_ModifierStackEvent = 19,
    k_eCitadelCombatLog_ActivatePowerup = 21,
    k_eCitadelCombatLog_HeroSaved = 23,
    k_eCitadelCombatLog_HeroLevelup = 25,
    k_eCitadelCombatLog_InterruptChannel = 28,
    k_eCitadelCombatLog_AlliedGold = 29,
    k_eCitadelCombatLog_RejuvTaken = 30,
    k_eCitadelCombatLog_UnitSummoned = 33,
    k_eCitadelCombatLog_EndKillstreak = 37,
    k_eCitadelCombatLog_CriticalDamage = 39,
    k_eCitadelCombatLog_SpellAbsorb = 40,
    k_eCitadelCombatLog_UnitTeleported = 41,
};
