#pragma once

enum ECurrencySource : uint32_t  // sizeof 0x4
{
    EInvalidDesc = -1,
    EItemPurchase = 0,
    EItemUpgrade = 1,
    EItemSale = 2,
    ETreasureChest = 3,
    EAbilityPurchase = 4,
    EStartingAmount = 5,
    ELevelUp = 6,
    ECheats = 7,
    EResetDeathPenalty = 8,
    EDroppedOnDeath = 9,
    EHeroSwap = 10,
    EPlayerKill = 11,
    EPlayerKillAssist = 12,
    EBossKill = 13,
    ELaneTrooperKill = 14,
    ENeutralTrooperKill = 15,
    ENeutralBossKill = 16,
    EDeniedFromEnemy = 17,
    EAssassinatePlayerKill = 18,
    EItemTrophyCollector = 19,
    EItemCultistSacrifice = 20,
    EItemGooseEgg = 21,
    EOrbPlayer = 22,
    EOrbDeny = 23,
    EOrbLaneTrooper = 24,
    EOrbNeutralTrooper = 25,
    EOrbTier1TrooperBoss = 26,
    EOrbTier2TrooperBoss = 27,
    EOrbBaseGuardians = 28,
    EOrbShrines = 29,
    EOrbTier3TrooperBoss = 30,
    EOrbDeployable = 31,
    EOrbTrophyKill = 32,
    EOrbTreasureChest = 33,
    EOrbSiegeTrooper = 34,
    EOrbSpawner = 35,
    ENeutralWorldPickup = 36,
    EBreakablePickup = 37,
    EPlayerKillComeback = 38,
    ETeamBonus = 39,
    EItemDraftRerollUsed = 40,
    EItemEnhacementUsed = 41,
    EStreetBrawlRoundReset = 42,
    ECurrencySourceCount = 43,
};
