#pragma once

enum EEconItemQuality : uint32_t  // sizeof 0x4
{
    AE_UNDEFINED = -1,
    AE_BASE = 0,
    AE_GENUINE = 1,
    AE_VINTAGE = 2,
    AE_UNUSUAL = 3,
    AE_UNIQUE = 4,
    AE_COMMUNITY = 5,
    AE_DEVELOPER = 6,
    AE_SELFMADE = 7,
    AE_CUSTOMIZED = 8,
    AE_STRANGE = 9,
    AE_COMPLETED = 10,
    AE_HAUNTED = 11,
    AE_TOURNAMENT = 12,
    AE_FAVORED = 13,
    AE_ASCENDANT = 14,
    AE_AUTOGRAPHED = 15,
    AE_LEGACY = 16,
    AE_EXALTED = 17,
    AE_FROZEN = 18,
    AE_CORRUPTED = 19,
    AE_LUCKY = 20,
    AE_INFUSED = 21,
    AE_GLITTER = 22,
    AE_HOLO = 23,
    AE_GOLD = 24,
    AE_MAX_TYPES = 25,
};
