#pragma once

enum EModifierScriptVariantType : uint32_t  // sizeof 0x4
{
    MODIFIER_SCRIPT_VARIANT_MODIFIER_FLOAT = 0,
    MODIFIER_SCRIPT_VARIANT_MODEL = 1,
    MODIFIER_SCRIPT_VARIANT_PARTICLE = 2,
    MODIFIER_SCRIPT_VARIANT_MODIFIER_BOOLEAN = 3,
    MODIFIER_SCRIPT_VARIANT_MODIFIER_INTEGER = 4,
};
