#pragma once

enum EntitySubclassScope_t : uint32_t  // sizeof 0x4
{
    SUBCLASS_SCOPE_NONE = -1,
    SUBCLASS_SCOPE_MISC = 0,
    SUBCLASS_SCOPE_PRECIPITATION = 1,
    SUBCLASS_SCOPE_MODIFIERS = 2,
    SUBCLASS_SCOPE_NPC_UNITS = 3,
    SUBCLASS_SCOPE_ABILITIES = 4,
    SUBCLASS_SCOPE_SCALE_FUNCTIONS = 5,
    SUBCLASS_SCOPE_LOOT_TABLES = 6,
    SUBCLASS_SCOPE_COUNT = 7,
};
