#pragma once

enum EShopGroups : uint32_t  // sizeof 0x4
{
    EMagazines = 0,
    EBulletVelocity = 1,
    EWeaponRange = 2,
    EHeadshotEnthusiasts = 3,
    ERateOfFire = 4,
    ESlowingBullets = 5,
    ETankingBullets = 6,
    ESpiritSlinger = 7,
    EMisc = 8,
    EActives = 9,
    EMoreHealth = 10,
    EHealing = 11,
    ERevitalization = 12,
    EDebuffs = 13,
    ESpiritProtection = 14,
    EBulletProtection = 15,
    ELifesteal = 16,
    EMelee = 17,
    EMovementAndAgility = 18,
    EAntiHealing = 19,
    EAdditionalProtection = 20,
    EMoreSpirit = 21,
    EBurstDamage = 22,
    ESpiritRange = 23,
    EDuration = 24,
    ECharges = 25,
    ECooldown = 26,
    EMeleeSpirit = 27,
    ESlowingMagic = 28,
    EMagicVulnerability = 29,
    ECrownControl = 30,
    EAntiGun = 31,
    EMiscSpirit = 32,
    ENotGrouped = 33,
};
