#pragma once

enum ETalentContentStatus : uint32_t  // sizeof 0x4
{
    TALENT_CONTENT_STATUS_INVALID = 0,
    TALENT_CONTENT_STATUS_PENDING = 1,
    TALENT_CONTENT_STATUS_EVALUATED = 2,
    TALENT_CONTENT_STATUS_REJECTED = 3,
    TALENT_CONTENT_STATUS_APPROVED = 4,
};
