#pragma once

enum ModifierSoundRecipients_t : uint32_t  // sizeof 0x4
{
    MODIFIER_SOUND_RECIPIENT_ALWAYS = 0,
    MODIFIER_SOUND_RECIPIENT_PARENT_IS_LOCAL_PLAYER = 1,
    MODIFIER_SOUND_RECIPIENT_PARENT_ON_SAME_TEAM_AS_LOCAL_PLAYER = 2,
    MODIFIER_SOUND_RECIPIENT_PARENT_ON_OPPOSITE_TEAM_AS_LOCAL_PLAYER = 3,
};
