#pragma once

enum ModifierAttribute_t : uint32_t  // sizeof 0x4
{
    MODIFIER_ATTRIBUTE_NONE = 0,
    MODIFIER_ATTRIBUTE_PERMANENT = 1,
    MODIFIER_ATTRIBUTE_MULTIPLE = 2,
    MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE = 4,
    MODIFIER_ATTRIBUTE_AURA_PRIORITY = 8,
    MODIFIER_ATTRIBUTE_CANNOT_BE_PURGED = 16,
    MODIFIER_ATTRIBUTE_INTRINSIC = 32,
    MODIFIER_ATTRIBUTE_TRANSFER_TO_RAGDOLL = 64,
};
