#pragma once

enum ModifierDisableGroup_t : uint32_t  // sizeof 0x4
{
    MODIFIER_DISABLE_GROUP_MIN = 0,
    MODIFIER_DISABLE_GROUP_ACTIVE_WEAPON = 1,
    MODIFIER_DISABLE_GROUP_TIME_LOCKED = 2,
    MODIFIER_DISABLE_GROUP_MAX_BIT = 1,
    MODIFIER_DISABLE_GROUP_MAX = 2,
};
