#pragma once

enum ModifierOverheadDrawType_t : uint32_t  // sizeof 0x4
{
    OVERHEAD_DRAW_NEVER = 0,
    OVERHEAD_DRAW_FOR_EVERYONE = 1,
    OVERHEAD_DRAW_FOR_CASTER_ONLY = 2,
    OVERHEAD_DRAW_FOR_CASTER_TEAM_ONLY = 3,
    OVERHEAD_DRAW_FOR_PARENT_TEAM_ONLY = 4,
    OVERHEAD_DRAW_OWNERS_OF_APPLYING_ABILITY = 5,
};
