#pragma once

class CSceneEntity : public CPointEntity /*0x0*/  // sizeof 0xAD0, align 0x8 [vtable] (server)
{
public:
    char _pad_0000[0x790]; // offset 0x0
    CUtlSymbolLarge m_iszSceneFile; // offset 0x790, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget1; // offset 0x798, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget2; // offset 0x7A0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget3; // offset 0x7A8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget4; // offset 0x7B0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget5; // offset 0x7B8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget6; // offset 0x7C0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget7; // offset 0x7C8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget8; // offset 0x7D0, size 0x8, align 8
    CHandle< CBaseEntity > m_hTarget1; // offset 0x7D8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget2; // offset 0x7DC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget3; // offset 0x7E0, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget4; // offset 0x7E4, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget5; // offset 0x7E8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget6; // offset 0x7EC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget7; // offset 0x7F0, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget8; // offset 0x7F4, size 0x4, align 4
    CHandle< CBaseEntity > m_hLocatorOrigin; // offset 0x7F8, size 0x4, align 4
    char _pad_07FC[0x4]; // offset 0x7FC
    CUtlSymbolLarge m_sTargetAttachment; // offset 0x800, size 0x8, align 8
    bool m_bIsPlayingBack; // offset 0x808, size 0x1, align 1
    bool m_bPaused; // offset 0x809, size 0x1, align 1
    bool m_bMultiplayer; // offset 0x80A, size 0x1, align 1
    bool m_bAutogenerated; // offset 0x80B, size 0x1, align 1
    float32 m_flForceClientTime; // offset 0x80C, size 0x4, align 4
    float32 m_flCurrentTime; // offset 0x810, size 0x4, align 4
    float32 m_flFrameTime; // offset 0x814, size 0x4, align 4
    bool m_bCancelAtNextInterrupt; // offset 0x818, size 0x1, align 1
    char _pad_0819[0x3]; // offset 0x819
    float32 m_fPitch; // offset 0x81C, size 0x4, align 4
    bool m_bAutomated; // offset 0x820, size 0x1, align 1
    char _pad_0821[0x3]; // offset 0x821
    int32 m_nAutomatedAction; // offset 0x824, size 0x4, align 4
    float32 m_flAutomationDelay; // offset 0x828, size 0x4, align 4
    float32 m_flAutomationTime; // offset 0x82C, size 0x4, align 4
    int32 m_nSpeechPriority; // offset 0x830, size 0x4, align 4
    bool m_bPausedViaInput; // offset 0x834, size 0x1, align 1
    bool m_bPauseAtNextInterrupt; // offset 0x835, size 0x1, align 1
    bool m_bWaitingForActor; // offset 0x836, size 0x1, align 1
    bool m_bWaitingForInterrupt; // offset 0x837, size 0x1, align 1
    bool m_bInterruptedActorsScenes; // offset 0x838, size 0x1, align 1
    bool m_bBreakOnNonIdle; // offset 0x839, size 0x1, align 1
    bool m_bSceneFinished; // offset 0x83A, size 0x1, align 1
    char _pad_083B[0x5]; // offset 0x83B
    CNetworkUtlVectorBase< CHandle< CBaseModelEntity > > m_hActorList; // offset 0x840, size 0x18, align 8
    CUtlVector< CHandle< CBaseEntity > > m_hRemoveActorList; // offset 0x858, size 0x18, align 8
    char _pad_0870[0x30]; // offset 0x870
    uint16 m_nSceneStringIndex; // offset 0x8A0, size 0x2, align 2 | MNotSaved
    char _pad_08A2[0x6]; // offset 0x8A2
    CEntityIOOutput m_OnStart; // offset 0x8A8, size 0x18, align 255
    CEntityIOOutput m_OnCompletion; // offset 0x8C0, size 0x18, align 255
    CEntityIOOutput m_OnCanceled; // offset 0x8D8, size 0x18, align 255
    CEntityIOOutput m_OnPaused; // offset 0x8F0, size 0x18, align 255
    CEntityIOOutput m_OnResumed; // offset 0x908, size 0x18, align 255
    CEntityIOOutput m_OnPulseRequirement; // offset 0x920, size 0x18, align 255
    char _pad_0938[0xF0]; // offset 0x938
    CUtlVector< ActorMapping_t > m_ActorMap; // offset 0xA28, size 0x18, align 8
    char _pad_0A40[0x28]; // offset 0xA40
    CHandle< CSceneEntity > m_hInterruptScene; // offset 0xA68, size 0x4, align 4
    int32 m_nInterruptCount; // offset 0xA6C, size 0x4, align 4
    bool m_bSceneMissing; // offset 0xA70, size 0x1, align 1 | MNotSaved
    bool m_bInterrupted; // offset 0xA71, size 0x1, align 1
    bool m_bCompletedEarly; // offset 0xA72, size 0x1, align 1
    bool m_bInterruptSceneFinished; // offset 0xA73, size 0x1, align 1
    bool m_bRestoring; // offset 0xA74, size 0x1, align 1 | MNotSaved
    char _pad_0A75[0x3]; // offset 0xA75
    CUtlVector< CHandle< CSceneEntity > > m_hNotifySceneCompletion; // offset 0xA78, size 0x18, align 8
    CUtlVector< CHandle< CSceneListManager > > m_hListManagers; // offset 0xA90, size 0x18, align 8
    CUtlSymbolLarge m_iszSoundName; // offset 0xAA8, size 0x8, align 8
    CUtlSymbolLarge m_iszSequenceName; // offset 0xAB0, size 0x8, align 8
    CHandle< CBaseModelEntity > m_hActor; // offset 0xAB8, size 0x4, align 4
    CHandle< CBaseEntity > m_hActivator; // offset 0xABC, size 0x4, align 4
    int32 m_BusyActor; // offset 0xAC0, size 0x4, align 4
    SceneOnPlayerDeath_t m_iPlayerDeathBehavior; // offset 0xAC4, size 0x4, align 4
    char _pad_0AC8[0x8]; // offset 0xAC8
};
