#pragma once

class CSceneEntity : public CPointEntity /*0x0*/  // sizeof 0xAC0, align 0x8 [vtable] (server)
{
public:
    char _pad_0000[0x780]; // offset 0x0
    CUtlSymbolLarge m_iszSceneFile; // offset 0x780, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget1; // offset 0x788, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget2; // offset 0x790, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget3; // offset 0x798, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget4; // offset 0x7A0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget5; // offset 0x7A8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget6; // offset 0x7B0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget7; // offset 0x7B8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget8; // offset 0x7C0, size 0x8, align 8
    CHandle< CBaseEntity > m_hTarget1; // offset 0x7C8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget2; // offset 0x7CC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget3; // offset 0x7D0, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget4; // offset 0x7D4, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget5; // offset 0x7D8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget6; // offset 0x7DC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget7; // offset 0x7E0, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget8; // offset 0x7E4, size 0x4, align 4
    CHandle< CBaseEntity > m_hLocatorOrigin; // offset 0x7E8, size 0x4, align 4
    char _pad_07EC[0x4]; // offset 0x7EC
    CUtlSymbolLarge m_sTargetAttachment; // offset 0x7F0, size 0x8, align 8
    bool m_bIsPlayingBack; // offset 0x7F8, size 0x1, align 1
    bool m_bPaused; // offset 0x7F9, size 0x1, align 1
    bool m_bMultiplayer; // offset 0x7FA, size 0x1, align 1
    bool m_bAutogenerated; // offset 0x7FB, size 0x1, align 1
    float32 m_flForceClientTime; // offset 0x7FC, size 0x4, align 4
    float32 m_flCurrentTime; // offset 0x800, size 0x4, align 4
    float32 m_flFrameTime; // offset 0x804, size 0x4, align 4
    bool m_bCancelAtNextInterrupt; // offset 0x808, size 0x1, align 1
    char _pad_0809[0x3]; // offset 0x809
    float32 m_fPitch; // offset 0x80C, size 0x4, align 4
    bool m_bAutomated; // offset 0x810, size 0x1, align 1
    char _pad_0811[0x3]; // offset 0x811
    int32 m_nAutomatedAction; // offset 0x814, size 0x4, align 4
    float32 m_flAutomationDelay; // offset 0x818, size 0x4, align 4
    float32 m_flAutomationTime; // offset 0x81C, size 0x4, align 4
    int32 m_nSpeechPriority; // offset 0x820, size 0x4, align 4
    bool m_bPausedViaInput; // offset 0x824, size 0x1, align 1
    bool m_bPauseAtNextInterrupt; // offset 0x825, size 0x1, align 1
    bool m_bWaitingForActor; // offset 0x826, size 0x1, align 1
    bool m_bWaitingForInterrupt; // offset 0x827, size 0x1, align 1
    bool m_bInterruptedActorsScenes; // offset 0x828, size 0x1, align 1
    bool m_bBreakOnNonIdle; // offset 0x829, size 0x1, align 1
    bool m_bSceneFinished; // offset 0x82A, size 0x1, align 1
    char _pad_082B[0x5]; // offset 0x82B
    CNetworkUtlVectorBase< CHandle< CBaseModelEntity > > m_hActorList; // offset 0x830, size 0x18, align 8
    CUtlVector< CHandle< CBaseEntity > > m_hRemoveActorList; // offset 0x848, size 0x18, align 8
    char _pad_0860[0x30]; // offset 0x860
    uint16 m_nSceneStringIndex; // offset 0x890, size 0x2, align 2 | MNotSaved
    char _pad_0892[0x6]; // offset 0x892
    CEntityIOOutput m_OnStart; // offset 0x898, size 0x18, align 255
    CEntityIOOutput m_OnCompletion; // offset 0x8B0, size 0x18, align 255
    CEntityIOOutput m_OnCanceled; // offset 0x8C8, size 0x18, align 255
    CEntityIOOutput m_OnPaused; // offset 0x8E0, size 0x18, align 255
    CEntityIOOutput m_OnResumed; // offset 0x8F8, size 0x18, align 255
    CEntityIOOutput m_OnPulseRequirement; // offset 0x910, size 0x18, align 255
    char _pad_0928[0xF0]; // offset 0x928
    CUtlVector< ActorMapping_t > m_ActorMap; // offset 0xA18, size 0x18, align 8
    char _pad_0A30[0x28]; // offset 0xA30
    CHandle< CSceneEntity > m_hInterruptScene; // offset 0xA58, size 0x4, align 4
    int32 m_nInterruptCount; // offset 0xA5C, size 0x4, align 4
    bool m_bSceneMissing; // offset 0xA60, size 0x1, align 1 | MNotSaved
    bool m_bInterrupted; // offset 0xA61, size 0x1, align 1
    bool m_bCompletedEarly; // offset 0xA62, size 0x1, align 1
    bool m_bInterruptSceneFinished; // offset 0xA63, size 0x1, align 1
    bool m_bRestoring; // offset 0xA64, size 0x1, align 1 | MNotSaved
    char _pad_0A65[0x3]; // offset 0xA65
    CUtlVector< CHandle< CSceneEntity > > m_hNotifySceneCompletion; // offset 0xA68, size 0x18, align 8
    CUtlVector< CHandle< CSceneListManager > > m_hListManagers; // offset 0xA80, size 0x18, align 8
    CUtlSymbolLarge m_iszSoundName; // offset 0xA98, size 0x8, align 8
    CUtlSymbolLarge m_iszSequenceName; // offset 0xAA0, size 0x8, align 8
    CHandle< CBaseModelEntity > m_hActor; // offset 0xAA8, size 0x4, align 4
    CHandle< CBaseEntity > m_hActivator; // offset 0xAAC, size 0x4, align 4
    int32 m_BusyActor; // offset 0xAB0, size 0x4, align 4
    SceneOnPlayerDeath_t m_iPlayerDeathBehavior; // offset 0xAB4, size 0x4, align 4
    char _pad_0AB8[0x8]; // offset 0xAB8
};
