#pragma once

enum AI_FacingTargetRequestSource_t : uint32_t  // sizeof 0x4
{
    eInvalid = -1,
    eMotor = 0,
    eChoreo = 1,
    eLevelScript = 2,
    eSchedule = 3,
    eMovement = 4,
    eStrategy = 5,
    eNpc = 6,
    eAutogenerated = 7,
    eAhead = 8,
    eCount = 9,
};
