#pragma once

enum AI_FacingTargetRequestSource_t : uint32_t  // sizeof 0x4
{
    eInvalid = -1,
    eMotor = 0,
    eChoreo = 1,
    eLevelScript = 2,
    eSmartGoal = 3,
    eSchedule = 4,
    eMoveStrategy = 5,
    eNavigator = 6,
    eNpc = 7,
    eAutogenerated = 8,
    eAhead = 9,
    eCount = 10,
};
