#pragma once

class CMapInfo : public CPointEntity /*0x0*/  // sizeof 0x4D8, align 0x8 [vtable] (server)
{
public:
    char _pad_0000[0x4A8]; // offset 0x0
    int32 m_iBuyingStatus; // offset 0x4A8, size 0x4, align 4
    float32 m_flBombRadius; // offset 0x4AC, size 0x4, align 4
    int32 m_iPetPopulation; // offset 0x4B0, size 0x4, align 4
    bool m_bUseNormalSpawnsForDM; // offset 0x4B4, size 0x1, align 1
    bool m_bDisableAutoGeneratedDMSpawns; // offset 0x4B5, size 0x1, align 1
    char _pad_04B6[0x2]; // offset 0x4B6
    float32 m_flBotMaxVisionDistance; // offset 0x4B8, size 0x4, align 4
    int32 m_iHostageCount; // offset 0x4BC, size 0x4, align 4
    bool m_bFadePlayerVisibilityFarZ; // offset 0x4C0, size 0x1, align 1
    bool m_bRainTraceToSkyEnabled; // offset 0x4C1, size 0x1, align 1
    bool m_bGPUCullSkybox; // offset 0x4C2, size 0x1, align 1
    char _pad_04C3[0x1]; // offset 0x4C3
    float32 m_flEnvRainStrength; // offset 0x4C4, size 0x4, align 4
    float32 m_flEnvPuddleRippleStrength; // offset 0x4C8, size 0x4, align 4
    float32 m_flEnvPuddleRippleDirection; // offset 0x4CC, size 0x4, align 4
    float32 m_flEnvWetnessCoverage; // offset 0x4D0, size 0x4, align 4
    float32 m_flEnvWetnessDryingAmount; // offset 0x4D4, size 0x4, align 4
};
