#pragma once

class CSceneEntity : public CPointEntity /*0x0*/  // sizeof 0x7E0, align 0x8 [vtable] (server)
{
public:
    char _pad_0000[0x4A0]; // offset 0x0
    CUtlSymbolLarge m_iszSceneFile; // offset 0x4A0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget1; // offset 0x4A8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget2; // offset 0x4B0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget3; // offset 0x4B8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget4; // offset 0x4C0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget5; // offset 0x4C8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget6; // offset 0x4D0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget7; // offset 0x4D8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget8; // offset 0x4E0, size 0x8, align 8
    CHandle< CBaseEntity > m_hTarget1; // offset 0x4E8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget2; // offset 0x4EC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget3; // offset 0x4F0, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget4; // offset 0x4F4, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget5; // offset 0x4F8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget6; // offset 0x4FC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget7; // offset 0x500, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget8; // offset 0x504, size 0x4, align 4
    CHandle< CBaseEntity > m_hLocatorOrigin; // offset 0x508, size 0x4, align 4
    char _pad_050C[0x4]; // offset 0x50C
    CUtlSymbolLarge m_sTargetAttachment; // offset 0x510, size 0x8, align 8
    bool m_bIsPlayingBack; // offset 0x518, size 0x1, align 1
    bool m_bPaused; // offset 0x519, size 0x1, align 1
    bool m_bMultiplayer; // offset 0x51A, size 0x1, align 1
    bool m_bAutogenerated; // offset 0x51B, size 0x1, align 1
    float32 m_flForceClientTime; // offset 0x51C, size 0x4, align 4
    float32 m_flCurrentTime; // offset 0x520, size 0x4, align 4
    float32 m_flFrameTime; // offset 0x524, size 0x4, align 4
    bool m_bCancelAtNextInterrupt; // offset 0x528, size 0x1, align 1
    char _pad_0529[0x3]; // offset 0x529
    float32 m_fPitch; // offset 0x52C, size 0x4, align 4
    bool m_bAutomated; // offset 0x530, size 0x1, align 1
    char _pad_0531[0x3]; // offset 0x531
    int32 m_nAutomatedAction; // offset 0x534, size 0x4, align 4
    float32 m_flAutomationDelay; // offset 0x538, size 0x4, align 4
    float32 m_flAutomationTime; // offset 0x53C, size 0x4, align 4
    int32 m_nSpeechPriority; // offset 0x540, size 0x4, align 4
    bool m_bPausedViaInput; // offset 0x544, size 0x1, align 1
    bool m_bPauseAtNextInterrupt; // offset 0x545, size 0x1, align 1
    bool m_bWaitingForActor; // offset 0x546, size 0x1, align 1
    bool m_bWaitingForInterrupt; // offset 0x547, size 0x1, align 1
    bool m_bInterruptedActorsScenes; // offset 0x548, size 0x1, align 1
    bool m_bBreakOnNonIdle; // offset 0x549, size 0x1, align 1
    bool m_bSceneFinished; // offset 0x54A, size 0x1, align 1
    char _pad_054B[0x5]; // offset 0x54B
    CNetworkUtlVectorBase< CHandle< CBaseModelEntity > > m_hActorList; // offset 0x550, size 0x18, align 8
    CUtlVector< CHandle< CBaseEntity > > m_hRemoveActorList; // offset 0x568, size 0x18, align 8
    char _pad_0580[0x30]; // offset 0x580
    uint16 m_nSceneStringIndex; // offset 0x5B0, size 0x2, align 2 | MNotSaved
    char _pad_05B2[0x6]; // offset 0x5B2
    CEntityIOOutput m_OnStart; // offset 0x5B8, size 0x18, align 255
    CEntityIOOutput m_OnCompletion; // offset 0x5D0, size 0x18, align 255
    CEntityIOOutput m_OnCanceled; // offset 0x5E8, size 0x18, align 255
    CEntityIOOutput m_OnPaused; // offset 0x600, size 0x18, align 255
    CEntityIOOutput m_OnResumed; // offset 0x618, size 0x18, align 255
    CEntityIOOutput m_OnPulseRequirement; // offset 0x630, size 0x18, align 255
    char _pad_0648[0xF0]; // offset 0x648
    CUtlVector< ActorMapping_t > m_ActorMap; // offset 0x738, size 0x18, align 8
    char _pad_0750[0x28]; // offset 0x750
    CHandle< CSceneEntity > m_hInterruptScene; // offset 0x778, size 0x4, align 4
    int32 m_nInterruptCount; // offset 0x77C, size 0x4, align 4
    bool m_bSceneMissing; // offset 0x780, size 0x1, align 1 | MNotSaved
    bool m_bInterrupted; // offset 0x781, size 0x1, align 1
    bool m_bCompletedEarly; // offset 0x782, size 0x1, align 1
    bool m_bInterruptSceneFinished; // offset 0x783, size 0x1, align 1
    bool m_bRestoring; // offset 0x784, size 0x1, align 1 | MNotSaved
    char _pad_0785[0x3]; // offset 0x785
    CUtlVector< CHandle< CSceneEntity > > m_hNotifySceneCompletion; // offset 0x788, size 0x18, align 8
    CUtlVector< CHandle< CSceneListManager > > m_hListManagers; // offset 0x7A0, size 0x18, align 8
    CUtlSymbolLarge m_iszSoundName; // offset 0x7B8, size 0x8, align 8
    CUtlSymbolLarge m_iszSequenceName; // offset 0x7C0, size 0x8, align 8
    CHandle< CBaseModelEntity > m_hActor; // offset 0x7C8, size 0x4, align 4
    CHandle< CBaseEntity > m_hActivator; // offset 0x7CC, size 0x4, align 4
    int32 m_BusyActor; // offset 0x7D0, size 0x4, align 4
    SceneOnPlayerDeath_t m_iPlayerDeathBehavior; // offset 0x7D4, size 0x4, align 4
    char _pad_07D8[0x8]; // offset 0x7D8
};
