#pragma once

class CSceneEntity : public CPointEntity /*0x0*/  // sizeof 0x800, align 0x8 [vtable] (server)
{
public:
    char _pad_0000[0x4B0]; // offset 0x0
    CUtlSymbolLarge m_iszSceneFile; // offset 0x4B0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget1; // offset 0x4B8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget2; // offset 0x4C0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget3; // offset 0x4C8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget4; // offset 0x4D0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget5; // offset 0x4D8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget6; // offset 0x4E0, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget7; // offset 0x4E8, size 0x8, align 8
    CUtlSymbolLarge m_iszTarget8; // offset 0x4F0, size 0x8, align 8
    CHandle< CBaseEntity > m_hTarget1; // offset 0x4F8, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget2; // offset 0x4FC, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget3; // offset 0x500, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget4; // offset 0x504, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget5; // offset 0x508, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget6; // offset 0x50C, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget7; // offset 0x510, size 0x4, align 4
    CHandle< CBaseEntity > m_hTarget8; // offset 0x514, size 0x4, align 4
    CHandle< CBaseEntity > m_hLocatorOrigin; // offset 0x518, size 0x4, align 4
    char _pad_051C[0x4]; // offset 0x51C
    CUtlSymbolLarge m_sTargetAttachment; // offset 0x520, size 0x8, align 8
    bool m_bIsPlayingBack; // offset 0x528, size 0x1, align 1
    bool m_bPaused; // offset 0x529, size 0x1, align 1
    bool m_bMultiplayer; // offset 0x52A, size 0x1, align 1
    bool m_bAutogenerated; // offset 0x52B, size 0x1, align 1
    float32 m_flForceClientTime; // offset 0x52C, size 0x4, align 4
    float32 m_flCurrentTime; // offset 0x530, size 0x4, align 4
    float32 m_flFrameTime; // offset 0x534, size 0x4, align 4
    bool m_bCancelAtNextInterrupt; // offset 0x538, size 0x1, align 1
    bool m_bRemoveOnCompletion; // offset 0x539, size 0x1, align 1
    char _pad_053A[0x2]; // offset 0x53A
    float32 m_fPitch; // offset 0x53C, size 0x4, align 4
    bool m_bAutomated; // offset 0x540, size 0x1, align 1
    char _pad_0541[0x3]; // offset 0x541
    int32 m_nAutomatedAction; // offset 0x544, size 0x4, align 4
    float32 m_flAutomationDelay; // offset 0x548, size 0x4, align 4
    float32 m_flAutomationTime; // offset 0x54C, size 0x4, align 4
    int32 m_nSpeechPriority; // offset 0x550, size 0x4, align 4
    bool m_bPausedViaInput; // offset 0x554, size 0x1, align 1
    bool m_bPauseAtNextInterrupt; // offset 0x555, size 0x1, align 1
    bool m_bWaitingForActor; // offset 0x556, size 0x1, align 1
    bool m_bWaitingForInterrupt; // offset 0x557, size 0x1, align 1
    bool m_bInterruptedActorsScenes; // offset 0x558, size 0x1, align 1
    bool m_bBreakOnNonIdle; // offset 0x559, size 0x1, align 1
    bool m_bSceneFinished; // offset 0x55A, size 0x1, align 1
    char _pad_055B[0x5]; // offset 0x55B
    CNetworkUtlVectorBase< CHandle< CBaseModelEntity > > m_hActorList; // offset 0x560, size 0x18, align 8
    CUtlVector< CHandle< CBaseEntity > > m_hRemoveActorList; // offset 0x578, size 0x18, align 8
    char _pad_0590[0x30]; // offset 0x590
    uint16 m_nSceneStringIndex; // offset 0x5C0, size 0x2, align 2 | MNotSaved
    char _pad_05C2[0x6]; // offset 0x5C2
    CEntityIOOutput m_OnStart; // offset 0x5C8, size 0x18, align 255
    CEntityIOOutput m_OnCompletion; // offset 0x5E0, size 0x18, align 255
    CEntityIOOutput m_OnCanceled; // offset 0x5F8, size 0x18, align 255
    CEntityIOOutput m_OnPaused; // offset 0x610, size 0x18, align 255
    CEntityIOOutput m_OnResumed; // offset 0x628, size 0x18, align 255
    CEntityIOOutput m_OnPulseRequirement; // offset 0x640, size 0x18, align 255
    char _pad_0658[0x78]; // offset 0x658
    CUtlDict< CUtlSymbolLarge > m_TargetNameMap; // offset 0x6D0, size 0x28, align 8
    CUtlDict< CUtlSymbolLarge > m_AnchorNameMap; // offset 0x6F8, size 0x28, align 8
    CUtlDict< CUtlSymbolLarge > m_ActorGraphMap; // offset 0x720, size 0x28, align 8
    CUtlDict< ActorClipEntry_t > m_ActorClipMap; // offset 0x748, size 0x28, align 8
    CUtlVector< ActorMapping_t > m_ActorMap; // offset 0x770, size 0x18, align 8
    CHandle< CSceneEntity > m_hInterruptScene; // offset 0x788, size 0x4, align 4
    int32 m_nInterruptCount; // offset 0x78C, size 0x4, align 4
    CUtlString m_responseConcept; // offset 0x790, size 0x8, align 8
    CUtlString m_responseCriteria; // offset 0x798, size 0x8, align 8
    bool m_bSceneMissing; // offset 0x7A0, size 0x1, align 1 | MNotSaved
    bool m_bInterrupted; // offset 0x7A1, size 0x1, align 1
    bool m_bCompletedEarly; // offset 0x7A2, size 0x1, align 1
    bool m_bInterruptSceneFinished; // offset 0x7A3, size 0x1, align 1
    bool m_bRestoring; // offset 0x7A4, size 0x1, align 1 | MNotSaved
    char _pad_07A5[0x3]; // offset 0x7A5
    CUtlVector< CHandle< CSceneEntity > > m_hNotifySceneCompletion; // offset 0x7A8, size 0x18, align 8
    CUtlVector< CHandle< CSceneListManager > > m_hListManagers; // offset 0x7C0, size 0x18, align 8
    CUtlSymbolLarge m_iszSoundName; // offset 0x7D8, size 0x8, align 8
    CUtlSymbolLarge m_iszSequenceName; // offset 0x7E0, size 0x8, align 8
    CHandle< CBaseModelEntity > m_hActor; // offset 0x7E8, size 0x4, align 4
    CHandle< CBaseEntity > m_hActivator; // offset 0x7EC, size 0x4, align 4
    int32 m_BusyActor; // offset 0x7F0, size 0x4, align 4
    SceneOnPlayerDeath_t m_iPlayerDeathBehavior; // offset 0x7F4, size 0x4, align 4
    char _pad_07F8[0x8]; // offset 0x7F8
};
