#pragma once

enum EAIScheduleFlags : uint32_t  // sizeof 0x4
{
    SCHEDULE_FLAGS_NONE = 0,
    SCHEDULE_FLAGS_ABILITY = 1,
    SCHEDULE_FLAGS_INTERRUPT_ACTIVE_HANDSHAKES = 2,
    SCHEDULE_FLAGS_CANNOT_BE_INTERRUPTED_BY_SYNCHRONIZED_ABILITY = 4,
    SCHEDULE_FLAGS_CANNOT_BE_INTERRUPTED_BY_INCAPACITATION = 8,
    SCHEDULE_FLAGS_NO_INTERRUPT_ON_NAV_FAILURE = 16,
    SCHEDULE_FLAGS_BODY_SECTION_MUTEX_FULL = 32,
    SCHEDULE_FLAGS_BODY_SECTION_MUTEX_UPPER = 64,
    SCHEDULE_FLAGS_BODY_SECTION_MUTEX_NONE = 128,
    SCHEDULE_FLAGS_IS_FORCED_GO_SCHEDULE = 256,
    SCHEDULE_FLAGS_ALLOW_CHOOSE_NEW_ENEMY = 512,
    SCHEDULE_FLAGS_DO_NOT_INTERRUPT_ON_BEHAVIOR_CHANGE_REQUEST = 1024,
    SCHEDULE_FLAGS_DO_NOT_INTERRUPT_ON_STRATEGY_CHANGE_REQUEST = 2048,
    SCHEDULE_FLAGS_NO_CUSTOM_INTERRUPTS = 4096,
    SCHEDULE_FLAGS_BODY_SECTION_MUTEX_NONE_EXPLICIT = 8192,
};
