#pragma once

class C_SceneEntity : public C_PointEntity /*0x0*/  // sizeof 0x7E8, align 0x8 [vtable] (client)
{
public:
    char _pad_0000[0x788]; // offset 0x0
    bool m_bIsPlayingBack; // offset 0x788, size 0x1, align 1 | MNotSaved
    bool m_bPaused; // offset 0x789, size 0x1, align 1 | MNotSaved
    bool m_bMultiplayer; // offset 0x78A, size 0x1, align 1 | MNotSaved
    bool m_bAutogenerated; // offset 0x78B, size 0x1, align 1 | MNotSaved
    bool m_bAllRequirementsComplete; // offset 0x78C, size 0x1, align 1 | MNotSaved
    char _pad_078D[0x3]; // offset 0x78D
    float32 m_flForceClientTime; // offset 0x790, size 0x4, align 4 | MNotSaved
    uint16 m_nSceneStringIndex; // offset 0x794, size 0x2, align 2 | MNotSaved
    bool m_bClientOnly; // offset 0x796, size 0x1, align 1 | MNotSaved
    char _pad_0797[0x1]; // offset 0x797
    CHandle< C_BaseModelEntity > m_hOwner; // offset 0x798, size 0x4, align 4 | MNotSaved
    char _pad_079C[0x4]; // offset 0x79C
    C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > > m_hActorList; // offset 0x7A0, size 0x18, align 8 | MNotSaved
    bool m_bWasPlaying; // offset 0x7B8, size 0x1, align 1 | MNotSaved
    char _pad_07B9[0xF]; // offset 0x7B9
    CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents; // offset 0x7C8, size 0x18, align 8 | MNotSaved
    float32 m_flCurrentTime; // offset 0x7E0, size 0x4, align 4 | MNotSaved
    char _pad_07E4[0x4]; // offset 0x7E4
};
