#pragma once

class C_SceneEntity : public C_PointEntity /*0x0*/  // sizeof 0x7D8, align 0x8 [vtable] (client)
{
public:
    char _pad_0000[0x778]; // offset 0x0
    bool m_bIsPlayingBack; // offset 0x778, size 0x1, align 1 | MNotSaved
    bool m_bPaused; // offset 0x779, size 0x1, align 1 | MNotSaved
    bool m_bMultiplayer; // offset 0x77A, size 0x1, align 1 | MNotSaved
    bool m_bAutogenerated; // offset 0x77B, size 0x1, align 1 | MNotSaved
    bool m_bAllRequirementsComplete; // offset 0x77C, size 0x1, align 1 | MNotSaved
    char _pad_077D[0x3]; // offset 0x77D
    float32 m_flForceClientTime; // offset 0x780, size 0x4, align 4 | MNotSaved
    uint16 m_nSceneStringIndex; // offset 0x784, size 0x2, align 2 | MNotSaved
    bool m_bClientOnly; // offset 0x786, size 0x1, align 1 | MNotSaved
    char _pad_0787[0x1]; // offset 0x787
    CHandle< C_BaseModelEntity > m_hOwner; // offset 0x788, size 0x4, align 4 | MNotSaved
    char _pad_078C[0x4]; // offset 0x78C
    C_NetworkUtlVectorBase< CHandle< C_BaseModelEntity > > m_hActorList; // offset 0x790, size 0x18, align 8 | MNotSaved
    bool m_bWasPlaying; // offset 0x7A8, size 0x1, align 1 | MNotSaved
    char _pad_07A9[0xF]; // offset 0x7A9
    CUtlVector< C_SceneEntity::QueuedEvents_t > m_QueuedEvents; // offset 0x7B8, size 0x18, align 8 | MNotSaved
    float32 m_flCurrentTime; // offset 0x7D0, size 0x4, align 4 | MNotSaved
    char _pad_07D4[0x4]; // offset 0x7D4
};
