#pragma once

class CMapInfo : public C_PointEntity /*0x0*/  // sizeof 0x7B0, align 0x8 [vtable] (client)
{
public:
    char _pad_0000[0x77C]; // offset 0x0
    int32 m_iBuyingStatus; // offset 0x77C, size 0x4, align 4
    float32 m_flBombRadius; // offset 0x780, size 0x4, align 4
    int32 m_iPetPopulation; // offset 0x784, size 0x4, align 4
    bool m_bUseNormalSpawnsForDM; // offset 0x788, size 0x1, align 1
    bool m_bDisableAutoGeneratedDMSpawns; // offset 0x789, size 0x1, align 1
    char _pad_078A[0x2]; // offset 0x78A
    float32 m_flBotMaxVisionDistance; // offset 0x78C, size 0x4, align 4
    int32 m_iHostageCount; // offset 0x790, size 0x4, align 4
    bool m_bFadePlayerVisibilityFarZ; // offset 0x794, size 0x1, align 1
    bool m_bRainTraceToSkyEnabled; // offset 0x795, size 0x1, align 1
    bool m_bGPUCullSkybox; // offset 0x796, size 0x1, align 1
    char _pad_0797[0x1]; // offset 0x797
    float32 m_flEnvRainStrength; // offset 0x798, size 0x4, align 4
    float32 m_flEnvPuddleRippleStrength; // offset 0x79C, size 0x4, align 4
    float32 m_flEnvPuddleRippleDirection; // offset 0x7A0, size 0x4, align 4
    float32 m_flEnvWetnessCoverage; // offset 0x7A4, size 0x4, align 4
    float32 m_flEnvWetnessDryingAmount; // offset 0x7A8, size 0x4, align 4
    char _pad_07AC[0x4]; // offset 0x7AC
};
