#pragma once

enum DOTAVisualNovelDialogueTextEffect_t : uint32_t  // sizeof 0x4
{
    VN_DIALOGUE_EFFECT_TEXT_NONE = 0,
    VN_DIALOGUE_EFFECT_TEXT_INSTANT = 1,
    VN_DIALOGUE_EFFECT_TEXT_FAST = 2,
    VN_DIALOGUE_EFFECT_TEXT_BOLD = 4,
    VN_DIALOGUE_EFFECT_TEXT_SMALL = 8,
    VN_DIALOGUE_EFFECT_TEXT_NO_NAMEPLATE = 16,
    VN_DIALOGUE_EFFECT_TEXT_NO_TEXT = 32,
};
