#pragma once

enum DOTAVisualNovelDialogueActorOverlayEffect_t : uint32_t  // sizeof 0x4
{
    VN_DIALOGUE_EFFECT_ACTOR_NONE = 0,
    VN_DIALOGUE_EFFECT_ACTOR_ANGER = 1,
    VN_DIALOGUE_EFFECT_ACTOR_ANXIETY = 2,
    VN_DIALOGUE_EFFECT_ACTOR_SWEATDROP = 4,
    VN_DIALOGUE_EFFECT_ACTOR_DAZED = 8,
    VN_DIALOGUE_EFFECT_ACTOR_SURPRISE = 16,
    VN_DIALOGUE_EFFECT_ACTOR_CONFUSED = 32,
    VN_DIALOGUE_EFFECT_ACTOR_ANNOYED = 64,
    VN_DIALOGUE_EFFECT_ACTOR_ASLEEP = 128,
    VN_DIALOGUE_EFFECT_ACTOR_SPARKLE = 256,
    VN_DIALOGUE_EFFECT_ACTOR_NOISY = 512,
    VN_DIALOGUE_EFFECT_ACTOR_SMOKE = 1024,
    VN_DIALOGUE_EFFECT_ACTOR_DEPRESSED = 2048,
    VN_DIALOGUE_EFFECT_ACTOR_POWER = 4096,
    VN_DIALOGUE_EFFECT_ACTOR_HUFF = 8192,
    VN_DIALOGUE_EFFECT_ACTOR_HEART = 16384,
    VN_DIALOGUE_EFFECT_ACTOR_POWERDOWN = 32768,
    VN_DIALOGUE_EFFECT_ACTOR_GASP = 65536,
};
