#pragma once

enum EOverworldAuditAction : uint32_t  // sizeof 0x4
{
    k_eOverworldAuditAction_Invalid = 0,
    k_eOverworldAuditAction_DevModifyTokens = 1,
    k_eOverworldAuditAction_DevClearInventory = 2,
    k_eOverworldAuditAction_DevGrantTokens = 3,
    k_eOverworldAuditAction_CompletePath = 4,
    k_eOverworldAuditAction_ClaimEncounterReward = 5,
    k_eOverworldAuditAction_DevResetNode = 6,
    k_eOverworldAuditAction_DevResetPath = 7,
    k_eOverworldAuditAction_MatchRewardsFull = 8,
    k_eOverworldAuditAction_MatchRewardsHalf = 9,
    k_eOverworldAuditAction_EventActionTokenGrant = 10,
    k_eOverworldAuditAction_TokenTraderLost = 11,
    k_eOverworldAuditAction_TokenTraderGained = 12,
    k_eOverworldAuditAction_EncounterRewardTokenCost = 13,
    k_eOverworldAuditAction_EncounterRewardTokenReward = 14,
    k_eOverworldAuditAction_SupportGrantTokens = 16,
    k_eOverworldAuditAction_TokenGiftSent = 17,
    k_eOverworldAuditAction_DevSetFortune = 18,
    k_eOverworldAuditAction_DevClearFortune = 19,
    k_eOverworldAuditAction_RequestFortune = 20,
    k_eOverworldAuditAction_ClaimFortuneReward = 21,
    k_eOverworldAuditAction_DevGrantFortuneTellerCoin = 22,
    k_eOverworldAuditAction_ClaimFortuneTellerStoryNodeReward = 23,
    k_eOverworldAuditAction_MatchRewardsAbilityDraft = 24,
    k_eOverworldAuditAction_MatchRewardsCoopBotMatch = 25,
};
