#pragma once

enum VMixAutoControlType_t : uint8_t  // sizeof 0x1
{
    VMIX_AUTO_SEND_LEVEL = 0,
    VMIX_AUTO_STACK_VAR = 1,
    VMIX_AUTO_PLAYTIME = 2,
    VMIX_AUTO_DISTANCE = 3,
    VMIX_AUTO_POSITION_X = 4,
    VMIX_AUTO_POSITION_Y = 5,
    VMIX_AUTO_POSITION_Z = 6,
    VMIX_AUTO_POSITION_VECTOR = 7,
    VMIX_AUTO_LISTENER_YAW_SIN = 8,
    VMIX_AUTO_LISTENER_YAW_COS = 9,
    VMIX_AUTO_LISTENER_PITCH_SIN = 10,
    VMIX_AUTO_LISTENER_PITCH_COS = 11,
    VMIX_AUTO_LISTENER_ROLL_SIN = 12,
    VMIX_AUTO_LISTENER_ROLL_COS = 13,
};
