#pragma once

enum ParticleOrientationSetMode_t : uint32_t  // sizeof 0x4
{
    PARTICLE_ORIENTATION_SET_NONE = -1,
    PARTICLE_ORIENTATION_SET_FROM_VELOCITY = 0,
    PARTICLE_ORIENTATION_SET_FROM_NORMAL = 1,
    PARTICLE_ORIENTATION_SET_FROM_ROTATIONS = 2,
};
