#pragma once

enum ParticleAttrBoxFlags_t : uint32_t  // sizeof 0x4
{
    PARTICLE_ATTR_BOX_FLAGS_NONE = 0,
    PARTICLE_ATTR_BOX_FLAGS_WATER = 1,
    PARTICLE_ATTR_BOX_FLAGS_ON_FIRE = 2,
    PARTICLE_ATTR_BOX_FLAGS_ELECTRIFIED = 4,
    PARTICLE_ATTR_BOX_FLAGS_ASLEEP = 8,
    PARTICLE_ATTR_BOX_FLAGS_FROZEN = 16,
    PARTICLE_ATTR_BOX_FLAGS_TIMED_DECAY = 32,
    PARTICLE_ATTR_BOX_FLAGS_DISABLE_NONSTATIC_COLLISION = 64,
    PARTICLE_ATTR_BOX_FLAGS_WAKE_DECAY = 128,
    PARTICLE_ATTR_BOX_FLAGS_MOTION_DISABLED = 256,
    PARTICLE_ATTR_BOX_FLAGS_ZERO_GRAVITY = 512,
};
