#pragma once

enum ParticleOmni2LighOrientationChoiceList_t : uint32_t  // sizeof 0x4
{
    PARTICLE_OMNI2_LIGHT_ORIENTATION_ROTATIONS = 0,
    PARTICLE_OMNI2_LIGHT_ORIENTATION_NORMAL = 1,
    PARTICLE_OMNI2_LIGHT_ORIENTATION_NORMAL_ROLL = 2,
    PARTICLE_OMNI2_LIGHT_ORIENTATION_TARGET = 3,
    PARTICLE_OMNI2_LIGHT_ORIENTATION_TARGET_ROLL = 4,
};
